Ostap_Solution
mate-academy/js_array-method-pop pull request #26
Opened 2019-04-15 09:38 UTC by ost-ptk

2019-04-15 18:47 UTC, vadim-ilchenko requested changes

2019-04-15 18:47 UTC, ivadimko commented on src/arrayMethodPop.js
> +    let a = this[this.length - 1];
Please avoid single-letter names
Probably you can move this code to `else` block along with `return a`. This way the code readability will increase.

2019-04-16 16:22 UTC, vadim-ilchenko approved these changes

2019-04-18 09:24 UTC, danmysak commented on src/arrayMethodPop.js
> +    if (this.length === 0) {
`if (this.length > 0)` без `return undefined` узагалі.

2025-09-22 15:27 UTC, closed without merging